---
name: release
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish the `unix-ts-macros` crate.
        run: cargo publish --package unix-ts-macros
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish the `unix-ts` crate.
        run: cargo publish --package unix-ts
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
